### ISSUE TITLE
These are only the Open Source Plugins of TinyMCE. do you have premium plugins?

### ISSUE THREAD

**Issue by faizanvahevaria** [GamerGirlandCo/fuck-you-tinymce#2]
https://www.tiny.cloud/docs/tinymce/6/plugins/

**Comment by GamerGirlandCo** [comment]
this repo contains both.

**Comment by GamerGirlandCo** [comment]
i updated everything last night, as i managed to write a script that fetches everything for me. now includes the ai plugin, among others :)
